version: "3"
services: 
    web:
        build: ./
        ports: 
            - "8080:8080"
        container_name: backend
    
    mongodb:
        image: "mongo"
        ports:
            - "27017:27017"
        container_name: mongo
        volumes:
        - ./mongodb/data/db/:/data/db/
        - ./mongodb/data/log/:/var/log/mongodb/
  