version: "3"
services: 
    web:
        build: ./
        ports: 
            - "8080:8080"
        container_name: backend
        volumes:
        - ./app:/go/src/github.com/sorathank/robinhood-assignment/app
    
    mongodb:
        build: ./db
        ports:
            - "27017:27017"
        container_name: mongo

    redis:
        image: "redis:latest"
        container_name: redis
